kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["*"] #,"apps","rbac.authorization.k8s.io","batch"]
    resources: ["pods"] #"deployment","pod","service"]
    verbs: ["get"] #"get","apply","delete","watch","create","patch"]
